import { applyDecorators } from '@nestjs/common';
import { ApiBody, ApiOkResponse, ApiOperation, ApiQuery, ApiSecurity } from '@nestjs/swagger';

import { CreateApiKeyDto } from '../dto/create-api-key.dto';
import { CreateWebhookDto } from '../dto/create-webhook.dto';

export function ApiListDeveloperKeys() {
  return applyDecorators(
    ApiOperation({ summary: 'List API keys for the current user' }),
    ApiSecurity('access-token'),
    ApiOkResponse({
      description: 'Developer API keys',
      schema: {
        example: [
          {
            id: 'key_123',
            name: 'Production key',
            keyPrefix: 'tasku_live_abcd1234',
            scopes: ['projects:read', 'tasks:write'],
            status: 'ACTIVE',
            usageCount: 120,
            lastUsedAt: '2026-06-01T09:00:00.000Z',
            expiresAt: null,
            createdAt: '2026-06-01T08:00:00.000Z',
          },
        ],
      },
    }),
  );
}

export function ApiCreateDeveloperKey() {
  return applyDecorators(
    ApiOperation({ summary: 'Create a new API key and return the secret once' }),
    ApiSecurity('access-token'),
    ApiBody({ type: CreateApiKeyDto }),
    ApiOkResponse({
      description: 'API key created',
      schema: {
        example: {
          id: 'key_123',
          name: 'Production key',
          keyPrefix: 'tasku_live_abcd1234',
          scopes: ['projects:read', 'tasks:write'],
          status: 'ACTIVE',
          key: 'tasku_live_super_secret',
          warning: 'developers.apiKey.storeNowWarning',
        },
      },
    }),
  );
}

export function ApiRevokeDeveloperKey() {
  return applyDecorators(
    ApiOperation({ summary: 'Revoke an API key' }),
    ApiSecurity('access-token'),
    ApiOkResponse({ schema: { example: { id: 'key_123', status: 'REVOKED' } } }),
  );
}

export function ApiDeveloperUsageSummary() {
  return applyDecorators(
    ApiOperation({ summary: 'Get API usage summary for the current user' }),
    ApiSecurity('access-token'),
    ApiOkResponse({
      schema: {
        example: {
          todayRequests: 42,
          monthRequests: 1820,
          errorRequests: 3,
          averageResponseMs: 118,
        },
      },
    }),
  );
}

export function ApiDeveloperRecentUsage() {
  return applyDecorators(
    ApiOperation({ summary: 'Get recent API traffic generated by API keys' }),
    ApiSecurity('access-token'),
    ApiQuery({ name: 'limit', required: false, example: 30 }),
  );
}

export function ApiDeveloperDocs() {
  return applyDecorators(
    ApiOperation({ summary: 'Get developer portal documentation payload' }),
    ApiSecurity('access-token'),
  );
}

export function ApiListWebhooks() {
  return applyDecorators(
    ApiOperation({ summary: 'List configured webhooks' }),
    ApiSecurity('access-token'),
  );
}

export function ApiCreateWebhook() {
  return applyDecorators(
    ApiOperation({ summary: 'Create a webhook with a signing secret' }),
    ApiSecurity('access-token'),
    ApiBody({ type: CreateWebhookDto }),
  );
}

export function ApiDisableWebhook() {
  return applyDecorators(
    ApiOperation({ summary: 'Disable a webhook' }),
    ApiSecurity('access-token'),
  );
}

export function ApiWebhookDeliveries() {
  return applyDecorators(
    ApiOperation({ summary: 'List recent webhook delivery attempts' }),
    ApiSecurity('access-token'),
    ApiQuery({ name: 'limit', required: false, example: 20 }),
  );
}
